Fix build on kernel 2.6.32 due to lack of discard_granularity
Build of nilfs2 kmod fails against vanilla kernel 2.6.32 due to lack
of discard_granularity parameter in queue_limits struct:

 fs/nilfs2/ioctl.c: In function 'nilfs_ioctl_trim_fs':
 fs/nilfs2/ioctl.c:1095:51: error: 'struct queue_limits' has no member named 'discard_granularity'
   range.minlen = max_t(u64, range.minlen, q->limits.discard_granularity);
                                                    ^
 include/linux/kernel.h:601:17: note: in definition of macro 'max_t'
   type __max2 = (y);   \
                  ^

This fixes the issue by using block-size instead of
discard_granularity for the 2.6.32 kernel.

Signed-off-by: Ryusuke Konishi <konishi.ryusuke@lab.ntt.co.jp>